# -*- coding: utf-8 -*-
"""43177_DL_A1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jJZ7TTghI_D_epXdrYydvfEc8l21aSjj

# **43177 STUTI KUMAR**

# **A1 - DL Packages**

## Install packages
"""

pip install tensorflow

pip install theano

pip install keras

pip install torch torchvision torchaudio

"""## Tensorflow"""

import tensorflow as tf

print(tf.__version__)

print(tf.reduce_sum(tf.random.normal([1000,2500])))

"""## Keras"""

from tensorflow import keras
from keras import datasets

(train_images, train_labels), (test_images, test_labels) = datasets.mnist.load_data()

train_images.shape

test_images.shape

"""## Theano"""

import numpy as np
import theano.tensor as T
from theano import function

#decalre variables
x = T.dscalar('x')
y = T.dscalar('y')

#define expression to be evaluation
z = x+y

#declare function
f = function([x,y],z)

#call function
f(5,7)

"""## PyTorch"""

import torch
import torch.nn as nn

print(torch.__version__)

torch.cuda.is_available()